![](shiva.jpg)

# __Problem Statement 1:__ 
In each of the following situations, state whether it is a correctly stated hypothesis 
testing problem and why?
1. 𝐻0: 𝜇 = 25, 𝐻1: 𝜇 ≠ 25
2. 𝐻0: 𝜎 > 10, 𝐻1: 𝜎 = 10
3. 𝐻0: 𝑥 = 50, 𝐻1: 𝑥 ≠ 50
4. 𝐻0: 𝑝 = 0.1, 𝐻1: 𝑝 = 0.5
5. 𝐻0: 𝑠 = 30, 𝐻1: 𝑠 > 30

__ANSWERS__
1. 𝐻0: 𝜇 = 25, 𝐻1: 𝜇 ≠ 25 => __This is correctly stated hypothesis__ because if the population mean (𝜇) of the null hypothesis (𝐻0) is 25 then the population mean(𝜇) of the alternative hypothesis (𝐻1) should not be 25 __i.e(𝜇<25 or 𝜇>25)__<br><br>
2. 𝐻0: 𝜎 > 10, 𝐻1: 𝜎 = 10 => __This is not correctly stated hypothesis__ because it states that in the null hypothesis (𝐻0)
the standard deviation (𝜎) is 10 so in the alternative hypothesis (𝐻1) the value of standard deviation (𝜎) should not be 10 __i.e (𝜎<10__)<br><br>
3. 𝐻0: 𝑥 = 50, 𝐻1: 𝑥 ≠ 50 => __This is correctly stated hypothesis__ as it states that if the value of 𝑥 in null hypothesis (𝐻0) is 50 then the value of 𝑥 in alternative hypothesis(𝐻1) should not be 50 __i.e (𝑥>50 or 𝑥<50)__<br><br>
4. 𝐻0: 𝑝 = 0.1, 𝐻1: 𝑝 = 0.5 => __This hypothesis is incorrectly stated__ as it states that the value of 𝑝 in null hypothesis (𝐻0) is 0.1
so in the alternative hypothesis (𝐻1) the value of p should not be equal to 0.1 __i.e the alternative hypothesis (𝐻1) should be (𝑝≠0.1)__<br><br>
5. 𝐻0: 𝑠 = 30, 𝐻1: 𝑠 > 30 => __This hypothesis is also incorrectly stated__ as it states that the value of 𝑠 in null hypothesis (𝐻0) is 30 so the value in alternative hypothesis (𝐻1) should not be 30 __i.e The alternative hypothesis (𝐻1) should be (𝑠≠30)__

# __Problem Statement 2:__
The college bookstore tells prospective students that the average cost of its 
textbooks is Rs. 52 with a standard deviation of Rs. 4.50. A group of smart statistics 
students thinks that the average cost is higher. To test the bookstore’s claim against 
their alternative, the students will select a random sample of size 100. Assume that 
the mean from their random sample is Rs. 52.80. Perform a hypothesis test at the 
5% level of significance and state your decision.

In [1]:
import pandas as pd
import numpy as np
import scipy.stats as st

In [2]:
def zstat(samp_mean,pop_mean,s_dev,n,z=-1.96,z1=1.96):#setting the default value for alpha as .05 so range is -1.96 to 1.96
    sample_error=s_dev/np.sqrt(n)
    ans=(samp_mean-pop_mean)/sample_error
    if ans<z or ans>z1:
        print(f"Reject the null hypothesis as the value do not fall between {z} and {z1}")
    else:
        print(f"Accept the null hypothesis as the value falls in between {z} and {z1}")
    print('Probability value',round(ans,2))

In [3]:
zstat(52.80,52,4.50,100)

Accept the null hypothesis as the value falls in between -1.96 and 1.96
Probability value 1.78


# Problem Statement 3: 
A certain chemical pollutant in the Genesee River has been constant for several 
years with mean μ = 34 ppm (parts per million) and standard deviation σ = 8 ppm. A 
group of factory representatives whose companies discharge liquids into the river is 
now claiming that they have lowered the average with improved filtration devices. A 
group of environmentalists will test to see if this is true at the 1% level of 
significance. Assume \ that their sample of size 50 gives a mean of 32.5 ppm. 
Perform a hypothesis test at the 1% level of significance and state your decision.

In [4]:
zstat(32.5,34,8,50,z=-2.58,z1=2.58)# alpha=1% so z score is 2.58 from the table

Accept the null hypothesis as the value falls in between -2.58 and 2.58
Probability value -1.33


# Problem Statement 4: 
Based on population figures and other general information on the U.S. population, 
suppose it has been estimated that, on average, a family of four in the U.S. spends 
about $1135 annually on dental expenditures. Suppose further that a regional dental 
association wants to test to determine if this figure is accurate for their area of 
country. To test this, 22 families of 4 are randomly selected from the population in 
that area of the country and a log is kept of the family’s dental expenditure for one 
year. The resulting data are given below. Assuming, that dental expenditure is 
normally distributed in the population, use the data and an alpha of 0.5 to test the 
dental association’s hypothesis.
1008, 812, 1117, 1323, 1308, 1415, 831, 1021, 1287, 851, 930, 730, 699,
872, 913, 944, 954, 987, 1695, 995, 1003, 994

In [5]:
def tstat(samp_mean,pop_mean,s_dev,n,t=-2.080,t1=2.080):#set the default value for alpha as .05
    sample_error=s_dev/np.sqrt(n)
    ans=(samp_mean-pop_mean)/sample_error
    if ans<t or ans>t1:
        print(f"Rejecting the null hypothesis\nConclusion is that there is a differnce\nAs the value do not fall in the range of {t} and {t1}")
    else:
        print(f"Accepting the null hypothesis\nConclusion is that there is no difference\nAs the value falls in the range of {t} and {t1}")
    print('Probability Value',round(ans,2))

In [6]:
sam_mean,std_dev=np.mean([1008, 812, 1117, 1323, 1308, 1415, 831, 1021, 1287, 851, 930, 730, 699, 872, 913, 944, 954, 987, 1695, 995, 1003, 994]),np.std([1008, 812, 1117, 1323, 1308, 1415, 831, 1021, 1287, 851, 930, 730, 699, 872, 913, 944, 954, 987, 1695, 995, 1003, 994])

In [7]:
tstat(samp_mean=sam_mean,pop_mean=1135,s_dev=std_dev,n=22) #pop_mean and n are given in the problem statment

Accepting the null hypothesis
Conclusion is that there is no difference
As the value falls in the range of -2.08 and 2.08
Probability Value -2.07


# Problem Statement 5: 
In a report prepared by the Economic Research Department of a major bank the 
Department manager maintains that the average annual family income on Metropolis 
is 48,432 (dollar). What do you conclude about the validity of the report if a random sample 
of 400 families shows and average income of $48,574 with a standard deviation of 
2000?

In [8]:
tstat(48574,48432,2000,400) #considering alpha=.05

Accepting the null hypothesis
Conclusion is that there is no difference
As the value falls in the range of -2.08 and 2.08
Probability Value 1.42


# Problem Statement 6:
Suppose that in past years the average price per square foot for warehouses in the 
United States has been 32.28 dollar. A national real estate investor wants to determine 
whether that figure has changed now. The investor hires a researcher who randomly 
samples 19 warehouses that are for sale across the United States and finds that the 
mean price per square foot is 31.67 dollar, with a standard deviation of 1.29 dollar. assume 
that the prices of warehouse footage are normally distributed in population. If the 
researcher uses a 5% level of significance, what statistical conclusion can be 
reached? What are the hypotheses?

In [9]:
tstat(31.67,32.28,1.29,19) #alpha is 0.5

Accepting the null hypothesis
Conclusion is that there is no difference
As the value falls in the range of -2.08 and 2.08
Probability Value -2.06


# Problem Statement 7:
Fill in the blank spaces in the table and draw your conclusions from it.

In [10]:
df=pd.DataFrame({'Acceptance region':['48.5<x<51.5','48<x<52','48.81<x<51.9','48.42<x<51.58'],'Sample Size':[10,10,16,16],'Alpha':[2.5,2.5,2.5,2.5],'Beta_at_𝜇=52':[0.2643,0,0.4960,0.2514],'Beta_at_𝜇=50.5':[0.8259,0.8586,0.9844,0.7319]})

In [11]:
df

Acceptance region  Sample Size  Alpha  Beta_at_𝜇=52  Beta_at_𝜇=50.5
0       48.5<x<51.5           10    2.5        0.2643          0.8259
1           48<x<52           10    2.5        0.0000          0.8586
2      48.81<x<51.9           16    2.5        0.4960          0.9844
3     48.42<x<51.58           16    2.5        0.2514          0.7319

# calculation of a value when Beta_at_𝜇=52	and 48.42<x<51.58	
* example - beta calculation when pop mean=52 and acceptance region is 48.42 < x < 51.58
* p1=48.42-52/(2.5/sqrt(16))= -5.728 we go to z table and find the z value which comes as 0
* p2=51.58-52/(2.5/sqrt(16))= -0.672 we go to z table and find the z value which comes as 0.2514
* finally we subtract (p2-p1) = 0.2514-0 we get value as 0.2514 __so beta when pop mean=52 and acceptance region is 48.42 < x < 51.58 =0.2514__
# similarly i have calculated for all 

# Problem Statement 8:
Find the t-score for a sample size of 16 taken from a population with mean 10 when 
the sample mean is 12 and the sample standard deviation is 1.5.

In [12]:
def tscore(samp_mean,pop_mean,s_dev,n):
    sample_error=s_dev/np.sqrt(n)
    ans=(samp_mean-pop_mean)/sample_error
    print(f"The t score is {round(ans,2)}")

In [13]:
tscore(12,10,1.5,16)

The t score is 5.33


# Problem Statement 9:
Find the t-score below which we can expect 99% of sample means will fall if samples 
of size 16 are taken from a normally distributed population.

In [14]:
t=st.t.ppf(q=0.99,df=15) #df=n-1=16-1=15
print("T score below which we can expect 99% of sample mean is",round(t,2))

T score below which we can expect 99% of sample mean is 2.6


# Problem Statement 10: 
If a random sample of size 25 drawn from a normal population gives a mean of 60 
and a standard deviation of 4, find the range of t-scores where we can expect to find 
the middle 95% of all sample means. Compute the probability that (−𝑡0.05 <𝑡<𝑡0.10).

In [15]:
# This is a two tailed test as we have to compare the probability between probability of (−𝑡 0.05 < 𝑡 < 𝑡 0.10).
n=25
mean=60
std_dev=4
t=round(st.t.ppf(0.95,24),4)# d0f=n=1=25-1=24
lower_cut_off=st.t.ppf(0.025,24,60,4) 
upper_cut_off=st.t.ppf(0.975,24,60,4)
print(f"T score below which we can expect 95% of sample mean is {lower_cut_off} to {upper_cut_off}")
print(f'T value is {t}\nProbability computation of P(−𝑡0.05 <𝑡<𝑡0.10) is\n(−𝑡0.05)=-2.064 is smaller than t value and t value ={t} is samller than (𝑡0.10)=1.711\nThe value of -2.064 and 1.711 i got from the t table')

T score below which we can expect 95% of sample mean is 51.74440575348792 to 68.25559424651209
T value is 1.7109
Probability computation of P(−𝑡0.05 <𝑡<𝑡0.10) is
(−𝑡0.05)=-2.064 is smaller than t value and t value =1.7109 is samller than (𝑡0.10)=1.711
The value of -2.064 and 1.711 i got from the t table


# Problem Statement 11:
Two-tailed test for difference between two population means
Is there evidence to conclude that the number of people travelling from Bangalore to 
Chennai is different from the number of people travelling from Bangalore to Hosur in 
a week, given the following:
Population 1: Bangalore to Chennai n1 = 1200
x1 = 452
s1 = 212
Population 2: Bangalore to Hosur n2 = 800
x2 = 523
s2 = 185

In [16]:
import numpy as np
#Two sampled t test
n1=1200 #number of people of population 1
x1=452 #mean of population 1
s1=212 #standard deviation of population 1
n2=800 #number of people of population 2
x2=523 #mean of population 2
s2=185 #standard deviation of population 2
#null hypothesis there is no difference between people travelling from banglore to chennai and banglore to hosur in a week
#alternative hypothesis there is difference between people travelling from banglore to chennai and banglore to hosur in a week
def two_sam_ttest(mean_1=0,mean_2=0,s_d1=0,s_d2=0,n1=0,n2=0,lower_bound=-1.9600,upper_bound=1.9600): #considering alpha value =0.5
    df1=n1-1
    df2=n2-1
    dof=df1+df2
    ss1=np.square(s_d1)*df1
    ss2=np.square(s_d2)*df2
    pooled_variance=(ss1+ss2)/(df1+df2)
    t=(mean_1-mean_2)/np.sqrt((pooled_variance/n1)+(pooled_variance)/n2)
    ans=(mean_1-mean_2)/np.sqrt((np.square(s_d1)/n1)+(np.square(s_d2)/n2))
    if ans<lower_bound or ans>upper_bound:
        print(f"Null hypothesis rejected as {round(ans,2)} do not fall in the range of {lower_bound} and {upper_bound}")
    else:
        print(f"Null hypothesis accepted as {round(ans,2)} falls in the range {lower_bound} and {upper_bound}")

In [17]:
two_sam_ttest(70,74,15,25,25,20)

Null hypothesis accepted as -0.63 falls in the range -1.96 and 1.96


# Problem Statement 12:
Is there evidence to conclude that the number of people preferring Duracell battery is 
different from the number of people preferring Energizer battery, given the following:
Population 1: Duracell
n1 = 100
x1 = 308
s1 = 84
Population 2: Energizer
n2 = 100
x2 = 254
s2 = 67

In [18]:
two_sam_ttest(308,254,84,67,100,100)

Null hypothesis rejected as 5.03 do not fall in the range of -1.96 and 1.96


# Problem Statement 13: 
Pooled estimate of the population variance
Does the data provide sufficient evidence to conclude that average percentage
increase in the price of sugar differs when it is sold at two different prices?
Population 1: Price of sugar = Rs. 27.50 n1 = 14
x1 = 0.317%
s1 = 0.12%
Population 2: Price of sugar = Rs. 20.00 n2 = 9
x2 = 0.21%
s2 = 0.11%

In [19]:
two_sam_ttest(27.50,20.00,12,11,14,9)

Null hypothesis accepted as 1.54 falls in the range -1.96 and 1.96


# Problem Statement 14:
The manufacturers of compact disk players want to test whether a small price 
reduction is enough to increase sales of their product. Is there evidence that the 
small price reduction is enough to increase sales of compact disk players?
Population 1: Before reduction
n1 = 15
x1 = Rs. 6598 s1 = Rs. 844
Population 2: After reduction n2 = 12
x2 = RS. 6870
s2 = Rs. 669

In [20]:
two_sam_ttest(6598,6870,844,669,15,12)

Null hypothesis accepted as -0.93 falls in the range -1.96 and 1.96


# Problem Statement 15: 
Comparisons of two population proportions when the hypothesized difference is zero 
Carry out a two-tailed test of the equality of banks’ share of the car loan market in 
1980 and 1995.
Population 1: 1980
n1 = 1000
x1 = 53
𝑝 1 = 0.53
Population 2: 1985
n2 = 100
x2 = 43
𝑝 2= 0.53

In [21]:
def two_samp_ztest(p1,p2,n1,n2,z1=-1.96,z2=1.96):#Considering alpha as 0.5
    prop_1=p1/n1
    prop_2=p2/n2
    pooled_prop=(p1+p2)/(n1+n2)
    z_val=(prop_1-prop_2)/((np.sqrt(pooled_prop*(1-pooled_prop)))*(np.sqrt(1/n1+1/n2)))
    if z_val<z1 or z_val>z2:
        print(f"Null hypothesis rejected as {round(z_val,3)} do not fall in the range of {z1} and {z2} as alpha value is considered as .05")
    else:
        print(f"Null hypothesis accepted as {round(z_val,3)} falls in the range of {z1} and {z2} as alpha value is considered as .05")

In [22]:
two_samp_ztest(53,43,1000,100)

Null hypothesis rejected as -12.736 do not fall in the range of -1.96 and 1.96 as alpha value is considered as .05


# Problem Statement 16: 
Carry out a one-tailed test to determine whether the population proportion of 
traveler’s check buyers who buy at least $2500 in checks when sweepstakes prizes 
are offered as at least 10 % higher than the proportion of such buyers when no 
sweepstakes are on.
Population 1: With sweepstakes
n1 = 300
x1 = 120
𝑝 = 0.40
Population 2: No sweepstakes n2 = 700
x2 = 140
𝑝 2= 0.20

In [23]:
two_samp_ztest(0.4,0.2,300,140)

Null hypothesis accepted as -0.025 falls in the range of -1.96 and 1.96 as alpha value is considered as .05


Problem Statement 17: 
A die is thrown 132 times with the following results: Number turned up: 1, 2, 3, 4, 5, 6
Frequency: 16, 20, 25, 14, 29, 28
Is the die unbiased? Consider the degrees of freedom as 𝑝 − 1.

In [24]:
#chi square test
#null hypothesis The dice is unbiased
#alternative hypothesis The dice is biased
dof=6-1
alpha=.05 #Considering
value=11.07

In [25]:
observed=[16,20,25,14,29,28]
expected=sum(observed)/len(observed)

In [26]:
chi_val=sum([(i-expected)**2/expected for i in observed])
if chi_val<value:
    print('Null hypothesis accepted the dice is unbiased')
else:
    print("Null hypothesis rejected the dice is biased")

Null hypothesis accepted the dice is unbiased


# Problem Statement 18: 
In a certain town, there are about one million eligible voters. A simple random 
sample of 10,000 eligible voters was chosen to study the relationship between 
gender and participation in the last election. The results are summarized in the 
following 2X2 (read two by two) contingency table:
We would want to check whether being a man or a woman (columns) is independent of 
having voted in the last election (rows). In other words, is “gender and voting independent”?

In [27]:
df=pd.DataFrame(data=[[2792,3591],[1486,2131]],index=['Voted','Not Voted'],columns=['Men','Women'])

In [28]:
observed=df.values

In [29]:
value=3.841 #Considering alpha as .05
chi_val,p_value,dof,exp_value=st.chi2_contingency(observed)
if chi_val>value:
    print("Null hypothesis rejected gender and voting are not independent")
else:
    print("Null hypothesis accepted gender and voting independent")

Null hypothesis rejected gender and voting are not independent


# Problem Statement 19: 
A sample of 100 voters are asked which of four candidates they would vote for in an 
election. The number supporting each candidate is given below:
Do the data suggest that all candidates are equally popular? Chi-Square = 14.96, 
with 3 df, 𝑝 0.05 .

In [30]:
#chi square test
data=[41,19,24,16]
chi_squre=14.96
dof=3
alpha=0.05
#as dof , alpha and chi square value is given we can get the value under which the chi square should be from the table
value=7.815
if chi_squre>value:
    print('Null hypothesis rejected and conclusion is that all candiates are not equally popular')
else:
    print("Null hypothesis accepted and conclusion is that all candidates are equally popular")

Null hypothesis rejected and conclusion is that all candiates are not equally popular


# Problem Statement 20:
Children of three ages are asked to indicate their preference for three photographs of 
adults. Do the data suggest that there is a significant relationship between age and 
photograph preference? What is wrong with this study? Chi-Square = 29.6, with 4 
df: 𝑝 < 0.05.

In [31]:
data=np.array([[18,22,20],[2,28,40],[20,10,40]])

In [32]:
value=9.488
chi_val=29.6
if chi_val>value:
    print('Null Hypothesis is rejected(There is a significant relationship between age and photograph preference)')
else:
    print("Null hypothesis is accepted (There is no significant relationship between age and photograph preference)")

Null Hypothesis is rejected(There is a significant relationship between age and photograph preference)


# Problem Statement 21: 
A study of conformity using the Asch paradigm involved two conditions: one where 
one confederate supported the true judgement and another where no confederate 
gave the correct response.
Is there a significant difference between the "support" and "no support" conditions in the 
frequency with which individuals are likely to conform? Chi-Square = 19.87, with 1 df:
𝑝 < 0.05.

In [33]:
#chi square test
data=np.array([[18,40],[32,10]])

In [34]:
chi_square=19.87
value=3.841
if chi_square>value:
    print("Null hypothesis is rejected there is a significant difference between 'support' and 'no support'")
else:
    print("Null hypothesis accepted there is no significant difference between 'support' and 'no support'")

Null hypothesis is rejected there is a significant difference between 'support' and 'no support'


# Problem Statement 22: 
We want to test whether short people differ with respect to their leadership qualities 
(Genghis Khan, Adolf Hitler and Napoleon were all stature-deprived, and how many midget 
MP's are there?) The following table shows the frequencies with which 43 short people and 
52 tall people were categorized as "leaders", "followers" or as "unclassifiable". Is there a 
relationship between height and leadership qualities? 
Chi-Square = 10.71, with 2 df: 𝑝 < 0.01.

In [35]:
#chi square test
data=np.array([[12,32],[22,14],[9,6]])

In [36]:
chi_square=10.71
value=9.210
if chi_square>value:
    print("Null hypothesis is rejected there is a relationship between height and leadership qualities :)")
else:
    print("Null hypothesis accepted there is no relation between height and leadership qualities")

Null hypothesis is rejected there is a relationship between height and leadership qualities :)


# Problem Statement 23: 
Each respondent in the Current Population Survey of March 1993 was classified as 
employed, unemployed, or outside the labor force. The results for men in California age 35-
44 can be cross-tabulated by marital status, as follows:
Men of different marital status seem to have different distributions of labor force status. Or is 
this just chance variation? (you may assume the table results from a simple random 
sample.)

In [37]:
#chi square test
df=pd.DataFrame(data=[[679,103,114],[63,10,20],[42,18,25]],index=['Employed','Unemployed','Not in labor Force'],columns=['Married','Widowed, divorced or seprated','Never Married'])

In [38]:
dof=4 #Considering alpha as .05
chi_val,p_value,dof,exp_value=st.chi2_contingency(observed)
value=9.488
if chi_val>value:
    print("Null hypothesis rejected (Marital status and employement status are dependent)")
else:
    print("Null hypothesis accepted (Marital status and employement status are not dependent)")

Null hypothesis accepted (Marital status and employement status are not dependent)
